modules:
  https://learn.med.uottawa.ca/courses/preventing-the-mistreatment-of-students/:
    name: Preventing the Mistreatment of Students
  https://apprendre.med.uottawa.ca/cours/prevention-de-la-maltraitance-des-etudiants-en-medecine/:
    name: Prévention de la maltraitance des étudiants en médecine
  